library(RPostgreSQL)
library(ggplot2)
library(tcltk)
library(getPass)
library(scales)

# non scientific numbers                                                      
options(scipen=999)
# set working directory
#folder_docs <- tk_choose.dir(default = "", caption = "Select working directory")
#setwd(folder_docs)
# connect to database
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, user='postgres', password=getPass::getPass(), dbname='dendrobox')
stat_dist_list <- dbGetQuery(con, "select * from distance_statistics")
# all species (LOG: `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")')
ggplot(stat_dist_list, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_r_all.png")
ggplot(stat_dist_list, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_r_all_trend.png")
ggplot(stat_dist_list, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_SGC_all.png")
ggplot(stat_dist_list, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_SGC_all_trend.png")
# Quercus sp.
distance_statistics_qusp <- dbGetQuery(con, "select * from distance_statistics_qusp")
ggplot(distance_statistics_qusp, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_r_QUSP.png")
ggplot(distance_statistics_qusp, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_r_QUSP_trend.png")
ggplot(distance_statistics_qusp, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_SGC_QUSP.png")
ggplot(distance_statistics_qusp, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_SGC_QUSP_trend.png")
# Pinus silvestris
distance_statistics_pisy <- dbGetQuery(con, "select * from distance_statistics_pisy")
ggplot(distance_statistics_pisy, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_r_PISY.png")
ggplot(distance_statistics_pisy, aes(x=distance_m, y=r)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_r_PISY_trend.png")
ggplot(distance_statistics_pisy, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001))
ggsave("Distance_SGC_PISY.png")
ggplot(distance_statistics_pisy, aes(x=distance_m, y=sgc)) + geom_point() + scale_x_continuous(label=unit_format(unit="km", scale=0.001)) + stat_smooth()
ggsave("Distance_SGC_PISY_trend.png")
